import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  sidebar: [
    {
      type: 'category',
      label: 'Meta',
      items: [
        {
          type: 'autogenerated',
          dirName: 'meta',
        }
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        }
      ],
    },
    {
      type: 'category',
      label: 'Upstream Docs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'upstream'
        }
      ],
    },
  ],
};

export default sidebars;
