import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  meta: [
    {
      type: 'category',
      label: 'About These Docs',
      link: {type: 'doc', id: 'index'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'setup/meta',
        }
      ],
    },
  ],
  setup: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'setup/getting-started'},
      items: [
        {
          type: 'autogenerated',
          dirName: 'setup/getting-started'
        }
      ]
    },
  ],
  guides: [
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        }
      ],
    },
  ],
  upstream: [
    {
      type: 'category',
      label: 'Upstream Docs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'upstream',
        }
      ],
    },
  ]
};

export default sidebars;
